### ISSUE TITLE
Yellow color appearing in frames after saving video with the VideoWriter

### ISSUE THREAD

**Issue by sumitanilkshirsagar** [vguzov/videoio#1]
Yellow color appearing in frames after saving video with the VideoWriter
I am running this on linux 18.04, Python 3.6.13 .
I will provide more info, just tell me what info is necessary

**Comment by vguzov** [comment]
Hi, can you provide a minimal example to reproduce?

**Comment by sumitanilkshirsagar** [comment]
```
import cv2
from videoio import VideoWriter
cap=cv2.VideoCapture(0)
ret,frame=cap.read()
width=frame.shape[1]
height=frame.shape[0]
out=VideoWriter("out.mp4",resolution=(width, height))
for i in range(100):
  ret,frame=cap.read()
  out.write(frame)
out.close()
```

**Comment by vguzov** [comment]
Thanks! In this example, OpenCV returns frames in BGR, while videoio assumes RGB, so blueish objects might seem yellow. Is that what you mean by yellow frames?

**Comment by sumitanilkshirsagar** [comment]
Yes. Bluish objects  are appearing yellow. Actually the video was underwater, so lot of it was blue color. So everything seemed yellow. Is there a flag I can pass to VideoWriter, telling it to expect BGR frames instead of RGB ? Or should I change the frames to RGB before ```out.write(frame)```

**Comment by vguzov** [comment]
No such flag, but you can just do `frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)` before passing it to `videoio`

**Comment by vguzov** [comment]
I suppose the problem is now resolved, let me know if not

**Comment by sumitanilkshirsagar** [comment]
Yes it's resolved. Thank you
