### ISSUE TITLE
Broken pipe error while using this library. Any Advice?

### ISSUE THREAD

**Issue by thiyophinj** [vguzov/videoio#2]
```self.ffmpeg_process.stdin.write(color_frame.tobytes()) BrokenPipeError: [Errno 32] Broken pipe```
I will provide  more info if necessary

**Comment by vguzov** [comment]
Hi, this means that ffmpeg process could not start correctly, most likely because libx264 was not enabled. If you are using conda, you can reinstall ffmpeg and add libx264 with the following commands:
```bash
conda remove ffmpeg
conda install ffmpeg x264 -c conda-forge
```
Hope that helps!

**Comment by vguzov** [comment]
I guess that helped, closing the issue
